# Generated by Django 2.2.16 on 2023-04-02 15:36

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230402_0004'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_cannot_follow_himself',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='user_cannot_follow_himself'),
        ),
    ]
